GET http://localhost:5230/games

###
GET http://localhost:5230/games/3

###
POST http://localhost:5230/games
Content-Type: application/json

{
  "name": "Street Fighter XIV",
  "genreId": 2,
  "price": 59.99,
  "releaseDate": "2010-09-30"
}

###
PUT http://localhost:5230/games/2
Content-Type: application/json

{
  "name": "Final Fantasy XIV",
  "genre": "Role-Playing",
  "price": 79.99,
  "releaseDate": "2010-09-30"
}

###
DELETE http://localhost:5230/games/1